#!/bin/bash

srcdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [ -d "$1" ] ; then
	dstdir="$1"
else
	dstdir="$HOME"
fi

dotfiles=(profile bash_logout bashrc
    vimrc gvimrc vim tmux.conf gitconfig cvsignore
    pylintrc latexmkrc ackrc
    pentadactyl pentadactylrc sqliterc
    i3/config i3status.conf config/dunstrc)

cd "$dstdir"
[ -d .i3 ]     || mkdir .i3
[ -d .config ] || mkdir .config
for file in "${dotfiles[@]}" ; do
    ln -siT "$srcdir/$file" ".$file"
done

cd "$dstdir/.vim"
[ -d tmp ]        || mkdir tmp
[ -d tmp/backup ] || mkdir tmp/backup
[ -d tmp/undo ]   || mkdir tmp/undo
[ -d tmp/swap ]   || mkdir tmp/swap

cd "$srcdir"
git submodule sync
git submodule update --init

