#!/bin/bash

srcdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"
if [[ -d "$1" ]] ; then
	dstdir="$1"
else
	dstdir="$HOME"
fi

dotfiles=(profile bash_logout bashrc
    vimrc gvimrc vim/bundle vim/python2 vim/syntax
    tmux.conf gitconfig hgrc cvsignore
    pylintrc latexmkrc ackrc ctags
    sqliterc psqlrc bowerrc
    i3/config.global config/dunstrc)

cd "$dstdir"

[ -d .i3 ]     || mkdir .i3
[ -d .config ] || mkdir .config

[[ -d .vim ]]            || mkdir .vim
[[ -d .vim/tmp ]]        || mkdir .vim/tmp
[[ -d .vim/tmp/backup ]] || mkdir .vim/tmp/backup
[[ -d .vim/tmp/undo ]]   || mkdir .vim/tmp/undo
[[ -d .vim/tmp/swap ]]   || mkdir .vim/tmp/swap

for file in "${dotfiles[@]}" ; do
    ln -siT "$srcdir/$file" ".$file"
done

touch .i3/config.local
touch .repo-dirs
ln -siT "$srcdir/profile" ".bash_profile"

cd "$srcdir"
git submodule sync
git submodule update --init

