#!/bin/bash

srcdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"
if [[ -d "$1" ]] ; then
    dstdir="$1"
    shift 1
else
    dstdir="$HOME"
fi

dotfiles=(profile bash_logout
    tmux.conf gitconfig hgrc cvsignore
    ackrc ctags.d sqliterc psqlrc)

dotfiles_extra=(gvimrc vim/bundle vim/python2 vim/syntax
    pylintrc xsettingsd gtkrc-2.0 i3/config.global
    config/gtk-3.0/settings.ini
    config/dunstrc
    config/zathura/zathurarc
    config/clipit/clipitrc
    config/termite/config
    "config/fish/functions")

cd "$dstdir"

[[ -d .vim ]]             || mkdir .vim
[[ -d .vim/tmp ]]         || mkdir .vim/tmp
[[ -d .vim/tmp/backup ]]  || mkdir .vim/tmp/backup
[[ -d .vim/tmp/undo ]]    || mkdir .vim/tmp/undo
[[ -d .vim/tmp/swap ]]    || mkdir .vim/tmp/swap
[[ -d .config/zathura ]]  || mkdir -p .config/zathura
[[ -d .config/clipit ]]   || mkdir -p .config/clipit
[[ -d .config/fish ]]     || mkdir -p .config/fish
[[ -d .config/gtk-3.0 ]]  || mkdir -p .config/gtk-3.0
[[ -d .config/termite ]]  || mkdir -p .config/termite

# Dont overwrite bashrc, vimrc, config.fish
if [[ ! -r .bashrc ]] ; then
    \cp -i "$srcdir/bashrc" ".bashrc"
fi
if [[ ! -r .vimrc ]] ; then
    \cp -i "$srcdir/vimrc" ".vimrc"
fi
if [[ ! -r .config/fish/config.fish ]] ; then
    \cp -i "$srcdir/config/fish/config.fish" ".config/fish/config.fish"
fi

for file in "${dotfiles[@]}" ; do
    ln -siT "$srcdir/$file" ".$file"
done
ln -siT "$srcdir/profile" ".bash_profile"

if [[ "$1" == "--extra" ]] ; then
    [ -d .i3 ]     || mkdir .i3
    [ -d .config ] || mkdir .config

    for file in "${dotfiles_extra[@]}" ; do
        ln -siT "$srcdir/$file" ".$file"
    done

    touch .i3/config.local
    touch .repo-dirs

    cd "$srcdir"
    git submodule sync
    git submodule update --init
fi
