#!/bin/bash

srcdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [ -d "$1" ] ; then
	dstdir="$1"
else
	dstdir="$HOME"
fi

dotfiles=(xinitrc bashrc_local i3/config.local)

cd "$dstdir"
for file in "${dotfiles[@]}" ; do
    ln -siT "$srcdir/$file" ".$file"
done
