execute "source " . expand("~/dotfiles/nvimrc.d/simple.lua")
execute "source " . expand("~/dotfiles/nvimrc.d/simple.vim")
execute "source " . expand("~/dotfiles/nvimrc.d/plugins.vim")
" execute "source " . expand("~/dotfiles/nvimrc.d/custom.vim")
" execute "source " . expand("~/dotfiles/vimrc.d/plugins_extra.vim")
