#!/bin/bash
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

export SHELL=/usr/bin/fish

# Setup i3
xrdb "$HOME/dotfiles/Xresources"
xrdb -merge <(echo "URxvt*perl-lib: $HOME/dotfiles/urxvt-perl/")
xrdb -merge <(echo "URxvt*perl-ext-common: 52-osc")

#xmodmap "$HOME/dotfiles/capslock-esc"
xmodmap "$HOME/dotfiles/print-insert"
eval `ssh-agent -s -t 16h`
dunst &
nitrogen --restore &
xscreensaver -no-splash &
#urxvtd -q -f -o
xsettingsd &

# exec gnome-session
# exec startkde
# exec startxfce4
# ...or the Window Manager of your choice

make-i3-config
exec i3 -V > "$HOME/.i3/i3log" 2>&1
