#!/bin/bash

srcdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [ -d "$1" ] ; then
	dstdir="$1"
else
	dstdir="$HOME"
fi

dotfiles=(xinitrc i3/config.local mpdconf config/ario/options.xml)

mkdir -p ~/.mpd/playlists
touch ~/.mpd/{database,log,pid,state,sticker.sql}

cd "$dstdir"
for file in "${dotfiles[@]}" ; do
    if [[ "$(dirname ".$file")" != "." ]] ; then
        mkdir -p "$(dirname ".$file")"
    fi
    ln -siT "$srcdir/$file" ".$file"
done
