#!/bin/bash

xrdb=xrdb
xinitdir=/etc/X11/xinit
xmodmap=xmodmap

userresources=$HOME/dotfiles/Xresources
usermodmap=$HOME/dotfiles/Xmodmap
sysresources=$xinitdir/.Xresources
sysmodmap=$xinitdir/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    if [ -x /usr/bin/cpp ] ; then
        $xrdb -merge $sysresources
    else
        $xrdb -nocpp -merge $sysresources
    fi
fi

if [ -f $sysmodmap ]; then
    $xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    if [ -x /usr/bin/cpp ] ; then
        $xrdb -merge "$userresources"
    else
        $xrdb -nocpp -merge "$userresources"
    fi
fi

if [ -f "$usermodmap" ]; then
    $xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d $xinitdir/xinitrc.d ] ; then
 for f in "$xinitdir/xinitrc.d"/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

export SHELL=/usr/bin/fish
export XDG_CURRENT_DESKTOP=GNOME

#xmodmap "$HOME/dotfiles/capslock-esc"
#xmodmap "$HOME/dotfiles/print-insert"
eval "$( ssh-agent -s -t 16h )"
dunst &
#xscreensaver -no-splash &
xsettingsd &
xcompmgr -c -l0 -t0 -r0 -o.00 &

# exec gnome-session
# exec startkde
# exec startxfce4
# ...or the Window Manager of your choice

mkdir -p "$HOME/.cache/i3"
exec i3 -V > "$HOME/.cache/i3/i3log" 2>&1
