#!/bin/bash

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

xrandr > /dev/null
xrandr --output eDP1 --mode 1920x1080
xinput set-prop  "SYNA2393:00 06CB:7A13 Touchpad" "libinput Tapping Enabled" 1

export SHELL=/usr/bin/fish

# Setup i3
xrdb "$HOME/dotfiles/Xresources"
#xrdb -merge <(echo "URxvt*perl-lib: $HOME/dotfiles/urxvt-perl/")
#xrdb -merge <(echo "URxvt*perl-ext-common: 52-osc")

#xmodmap "$HOME/dotfiles/capslock-esc"
#xmodmap "$HOME/dotfiles/print-insert"
eval `ssh-agent -s -t 16h`
dunst &
nitrogen --restore &
#xscreensaver -no-splash &
#urxvtd -q -f -o
xsettingsd &

# exec gnome-session
# exec startkde
# exec startxfce4
# ...or the Window Manager of your choice

make-i3-config
exec i3 -V > "$HOME/.i3/i3log" 2>&1
